### ISSUE TITLE
Mainnet not working well

### ISSUE THREAD

**Issue by morrigan** [niftyhorde/subgraphs#1]
I can't load any NFTs with the `https://api.thegraph.com/subgraphs/name/amxx/eip721-subgraph` API.

Not sure what's happening there but for example this address `0xAf0f557a9a7E84Bdd02aDBc14962df2789d95D4e` should have:
* axie infinity nfts
* ether cards
* postereum
* postereum v2
* ...

but getting response:

```
{
    "data": {
        "account": null
    }
}
```

**Comment by mpetrun5** [comment]
Lowercase
